{% set name = "google-cloud-pubsub" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b3d9336afab0e5df67201234976519a28da3ccb7c9a0e463be28e2827a9fdaa

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - libcst >=0.3.10
    - proto-plus >=1.7.1
    - grpcio >=1.38.1,<2.0dev

test:
  imports:
    - google.api_core
    - google.cloud.pubsub
    - grpc

about:
  home: https://pypi.org/project/google-cloud-pubsub/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Pub / Sub
  dev_url: https://github.com/googleapis/python-pubsub
  description: |
    Google Cloud Pub / Sub is a fully-managed real-time messaging service that
    allows you to send and receive messages between independent applications.
    You can leverage Cloud Pub/Sub’s flexibility to decouple systems and
    components hosted on Google Cloud Platform or elsewhere on the Internet. By
    building on the same technology Google uses, Cloud Pub / Sub is designed to
    provide “at least once” delivery at low latency with on-demand scalability
    to 1 million messages per second (and beyond).


extra:
  recipe-maintainers:
    - hmaarrfk
